services:
  node:
    container_name: node
    image: node:26-alpine3.24
    working_dir: /front
    volumes: 
      - ./:/front
    ports:
      - "3000:3000"
    tty: true
    networks:
      - myapp

  postgres:
    container_name: postgres
    image: postgres:15.4-alpine3.24
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextcicd
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    networks:
      - myapp

  redis:
    container_name: redis
    image: redis:8.8-alpine3.23
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    environment:
      - REDIS_ARG=redisarg
    networks:
      - myapp

networks:
  myapp:
    driver: bridge

volumes:
  pgdata:
